# This is a basic workflow that is manually triggered

name: Manual workflow

env:
  CLANG_VERSION: 15.0.6
  LLVM_VERSION: 17.0.6
  
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Dummy input'
        # Default value if no value is explicitly provided
        default: 'run you fool!'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build-native:
    # The type of runner that the job will run on
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    # - name: Send greeting
      # run: echo "Hello from Microsoft, we own you bitch!"
    - uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 50
          
    - name: Install prerequisites
      uses: ./.github/actions/1-setup
      with:
        clang_version: 16.0.6
        llvm_version: 19.1.5
        arch: x64

    - name: Build bootstrap LDC
      uses: ./.github/actions/2-build-bootstrap
      with:
        cmake_flags: -DBUILD_LTO_LIBS=ON
        arch: x64

    - name: Build LDC & LDC D unittests & defaultlib unittest runners
      uses: ./.github/actions/3-build-native
      with:
        cmake_flags: -DBUILD_LTO_LIBS=ON "-DD_COMPILER_FLAGS=-O -flto=full -defaultlib=phobos2-ldc-lto,druntime-ldc-lto" -DEXTRA_CXXFLAGS=-flto=full
        arch: x64
        with_pgo: false
